build: enforce annotated tags

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,6 +30,28 @@ jobs:
     - uses: actions/setup-python@v4
       with:
         python-version: '3.x'
+    - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
+      id: changes
+      name: Check annotated tag
+      run: |
+        title=$(git for-each-ref --format="%(contents:subject)" ${GITHUB_REF})
+        body=$(git for-each-ref --format="%(contents:body)" ${GITHUB_REF})
+        tag="${GITHUB_REF#refs/tags/}"
+        if test "$title" = "Version ${tag#v}" -a -n "$body"; then
+          echo "title=$title" >> "$GITHUB_OUTPUT"
+          echo "body=$body" >> "$GITHUB_OUTPUT"
+        else
+          echo "::error title=Missing tag annotation::$tag"
+          changelog=$(git log --pretty='format:%d%n- %s%n%b---' $(git tag --sort=v:refname | tail -n2 | head -n1)..HEAD)
+          cat <<EOF >> "$GITHUB_STEP_SUMMARY"
+        # Missing tag annotation
+        ## Fix
+        See <https://github.com/paskino/qt-elements/tree/main/.github/workflows#releasing>.
+        ## Suggested body
+        $changelog
+        EOF
+          exit 1
+        fi
     - id: dist
       uses: casperdcl/deploy-pypi@v2
       with:
@@ -38,9 +60,12 @@ jobs:
         upload: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
     - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
       name: Release
-      run: |
-        changelog=$(git log --pretty='format:%d%n- %s%n%b---' $(git tag --sort=v:refname | tail -n2 | head -n1)..HEAD)
-        tag="${GITHUB_REF#refs/tags/}"
-        gh release create --title "Version $tag" --draft --notes "$changelog" "$tag" dist/${{ steps.dist.outputs.whl }} dist/${{ steps.dist.outputs.targz }}
+      run: >
+        gh release create
+        --title "${{ steps.changes.outputs.title }}"
+        --notes "${{ steps.changes.outputs.body }}"
+        "${GITHUB_REF#refs/tags/}"
+        dist/${{ steps.dist.outputs.whl }}
+        dist/${{ steps.dist.outputs.targz }}
       env:
         GH_TOKEN: ${{ secrets.GH_TOKEN || github.token }}
